### ISSUE TITLE
How to install it?

### ISSUE THREAD

**Issue by GildedHonour** [maliutin/ComAddinShim#1]
How to install it?

**Comment by maliutin** [comment]
It is not a clear question.

If you mean the registry then there is the example in [ConnectProxy.rgs](https://github.com/maliutin/ComAddinShim/blob/master/Excel/ExcelAddin/ConnectProxy.rgs)

setup-shim.cmd contains the example of the command:
https://github.com/maliutin/ComAddinShim/blob/172b0914404b6982c0f50a1034bc14c0369830df/Excel/ISI.CdmNextAddin.ExcelAddin/setup-shim.cmd#L1
