### ISSUE TITLE
compilation issue

### ISSUE THREAD

**Issue by ZXF150811** [maliutin/ComAddinShim#2]
Hi  maliutin, 

After i clone this project, i got below compile issue, i hope to get feedback from your side about how can i solve this issue, thank you in advance!

3>stdafx.cpp
3>ExcelAddin.cpp
3>ConnectProxy.cpp
3>c:\zfan_190408\xxx\comaddinshim-master-2\comaddinshim-master\excel\exceladdin\connectproxy.h(23): error C2440: 'static_cast': cannot convert from 'CConnectProxy::_ComMapClass *' to 'AddInDesignerObjects::IDTExtensibility2 *'
3>c:\zfan_190408\xxx\comaddinshim-master-2\comaddinshim-master\excel\exceladdin\connectproxy.h(23): note: Types pointed to are unrelated; conversion requires reinterpret_cast, C-style cast or function-style cast
3>c:\zfan_190408\xxx\comaddinshim-master-2\comaddinshim-master\excel\exceladdin\connectproxy.h(26): error C2440: 'initializing': cannot convert from 'ATL::_ATL_CREATORARGFUNC (__stdcall *)' to 'DWORD_PTR'
3>c:\zfan_190408\xxx\comaddinshim-master-2\comaddinshim-master\excel\exceladdin\connectproxy.h(26): note: There is no context in which this conversion is possible
3>CLRLoader.cpp
3>Generating Code...
3>Done building project "ExcelAddin.vcxproj" -- FAILED.
========== Rebuild All: 2 succeeded, 1 failed, 0 skipped ==========

**Comment by maliutin** [comment]
Hi

I guess you are using VS 2019, do I?
It needs VS 2017 and the Windows SDK version 10.0.17134.0.

For new version VS and SDK I have not supported it.

**Comment by ZXF150811** [comment]
Hi Maliutin, 

I'm using the same tooling version as you mentioned above, please help to double confirm the below picture. 

![image](https://user-images.githubusercontent.com/13792657/84742510-1ac86880-afe3-11ea-804e-c2a13a4a5a6a.png)

**Comment by maliutin** [comment]
Another idea. Do you have the Microsoft Office? What version is?

I guess that the office package should be installed as an old version, for example, Office 2010 or 2013.

As I know, Office from the Microsoft store is installed with restrictions. Unfortunately, I cannot test it now. I don't have a prepared environment.

**Comment by ZXF150811** [comment]
yes, you're right, i'm using office 16. 
ok, thanks your clarify.

**Comment by ZXF150811** [comment]
> Another idea. Do you have the Microsoft Office? What version is?
> 
> I guess that the office package should be installed as an old version, for example, Office 2010 or 2013.
> 
> As I know, Office from the Microsoft store is installed with restrictions. Unfortunately, I cannot test it now. I don't have a prepared environment.

Hi Maliutin, 

We tested on VS 2017 + office 13 + Windows SDK version 10.0.17134.0, and **office-13 32 bits, the compile error gone**, While before **office-13 was 64 bits**, do you have some comments regarding to the difference ? 

Thanks your kindly support.

**Comment by maliutin** [comment]
Weird. I have loaded the source and it is compiled:
![image](https://user-images.githubusercontent.com/10669340/84992290-62b8ce00-b150-11ea-9c76-3e5e14fcfd9b.png)

My configuration:
- Windows 10 x64
- Office 2019 x86 (from Microsoft Store)

**Comment by maliutin** [comment]
Please, go to Visual Studio Installer and check the following component are installed:
- Office developer tools for Visual Studio
- The Visual Studio tools for Office (VSTO)

You can find them if you entre `office` in the search field.

**Comment by maliutin** [comment]
O. Maybe I found a problem. 

VS should be run under Admin rights.

Yep. In normal mode, I see your error.

**Comment by ZXF150811** [comment]
> O. Maybe I found a problem.
> 
> VS should be run under Admin rights.
> 
> Yep. In normal mode, I see your error.

Hi Maliutin, 

Thank you so much! 
Please let me know that if you're happen to visit Shenzhen China,  i'd like to invite you to have a beer.
