### ISSUE TITLE
More details for supporting and Thanks

### ISSUE THREAD

**Issue by lurkane2016** [maliutin/ComAddinShim#3]
hi，maliutin,
I'm here to disturb you again.
i 'm a  office excel develop fan. Earlier this year, I learned about shim comaddin on the Microsoft website（link：https://docs.microsoft.com/en-us/previous-versions/office/developer/office-2007/bb508939(v=office.12），and I have been concerned about your recent reply to new issue，like you.
I am a c# fan, but know nothing about c++, so the c++ project in your solution  is very difficult for me.
For unknown reasons, it is not easy for me to log in to the github. in order to getting your support or more details and thanks for your kindly reply to the last issue submitter（in fact，my good friend）, I sign up this github account.
I tested ok on another machine, it has the same configuration as you noted.
Now I have two puzzles that need your  continued support:
1.  How to upgrade the project to support my sdk version is 10.0.17763.0, because my os environment is win10 1905.It would be nice if some more detailed explanations were given, or email me.（my email:zhangwx.2014@foxmail.com） Thanks a lot.
2. Does this support the IRibbonExtensibility interface? Microsoft's wizard tool only updated to vs2010,and I noticed that net framework  default ver  is 3.5 in this project（ManagedAggregator is .net 2.0）, I change to 4.0 in the same configuration os Machine，seems  ok。I am confused about this, hope you can tell me your considerations? 
Asked a bit more, but I look forward to your reply.Thanks again.

**Comment by maliutin** [comment]
Hi

> How to upgrade the project to support my sdk version is 10.0.17763.0, because my os environment is win10 1905.

I think it is easy. You can choose the last version of Windows SDK that is installed on your machine:
![image](https://user-images.githubusercontent.com/10669340/85106212-7fb6d500-b214-11ea-94e3-1cd8bdd75edd.png)

10.0.17763.0 version was last when I worked with this tool.

> Does this support the IRibbonExtensibility interface? Microsoft's wizard tool only updated to vs2010,and I noticed that net framework default ver is 3.5 in this project（ManagedAggregator is .net 2.0）, I change to 4.0 in the same configuration os Machine，seems ok。I am confused about this, hope you can tell me your considerations?

I have not used Microsoft VSTO long time. Instead, I used NetOfficeFw - C# wrappers on COM Office objects. They allow supporting Office from 2007 version. Please don't confuse it with NetOffice. They are different projects.
